"""Turn-level configuration and the user-facing copy the engine can emit.

Everything a visitor might read that is *not* generated by a model lives here:
refusal texts, the escalation text, the greeting and the suggestion chips. One
file means the copy can be reviewed without reading the graph, and the graph
never inlines a sentence.

The greeting, the chips and the contact URL are re-exported from
`app.persona` rather than restated: they are the persona's copy, and the
brain has to be able to answer for every chip `/config` advertises. One
definition, imported one way — persona never imports this module back.
"""

from __future__ import annotations

import os

from app.persona import CONTACT_URL, GREETING, SUGGESTIONS

__all__ = [
    "CONTACT_URL",
    "GREETING",
    "SUGGESTIONS",
]

# Mirrored by the web composer's cap; keep the two equal or the client will
# happily send a message the server refuses.
MAX_INPUT_LEN = 2000

# Answers stream in fragments so the client exercises its incremental-render
# path. A single-chunk reply would let a broken token handler pass unnoticed.
CHUNK_SIZE = 8

# Comment heartbeat cadence while a step is slow. Keeps intermediaries from
# reaping an idle-looking connection — it does not extend CloudFront's hard 60s
# origin-response cap (KB-004), which is a budget for the whole turn.
PING_INTERVAL_S = 15.0

# Per-instance turn budget. One Lambda invoke serves one request and instances
# are short-lived, so a sliding window per client is enough to blunt a flood
# without a distributed store (plan.md defers a DynamoDB token bucket).
RATE_LIMIT_TURNS = int(os.environ.get("CADRE_RATE_LIMIT_TURNS", "30"))
RATE_LIMIT_WINDOW_S = float(os.environ.get("CADRE_RATE_LIMIT_WINDOW_S", "60"))

# ── Bedrock ────────────────────────────────────────────────────────────────
#
# One model per step, sized to the job (plan.md's roster). Every id below was
# verified against `bedrock list-foundation-models` and
# `list-inference-profiles` in us-east-1; `scripts/assert_models.py` re-checks
# them against the target account before an image is ever pushed, because every
# model step fails open and a wrong id therefore ships as a *working* chat with
# amber rails rather than as a crash (KB-009).
#
# The `us.` prefix on the Anthropic ids is load-bearing: those models report
# `inferenceTypesSupported: [INFERENCE_PROFILE]`, so the bare
# `anthropic.claude-…` id is not invokable — it resolves only through the
# cross-region inference profile.

BEDROCK_REGION = os.environ.get("CADRE_BEDROCK_REGION", "us-east-1")

# Cheap SLM sanity/validity judge, second half of `validate_input`.
MODEL_VALIDATE = os.environ.get("CADRE_MODEL_VALIDATE", "nvidia.nemotron-nano-9b-v2")

# Strict single-token prompt-injection classifier. Instruction-following
# against adversarial input is the whole job, so this one is a Claude.
MODEL_INJECTION = os.environ.get(
    "CADRE_MODEL_INJECTION", "us.anthropic.claude-haiku-4-5-20251001-v1:0"
)

# Three-way route: in_scope / off_topic / needs_human.
MODEL_TOPIC = os.environ.get("CADRE_MODEL_TOPIC", "nvidia.nemotron-nano-12b-v2")

# Walked in order when the primary classifier *errors*. Different provider
# first: a fallback that shares the primary's provider shares its outage.
MODEL_TOPIC_FALLBACKS = [
    model_id.strip()
    for model_id in os.environ.get(
        "CADRE_MODEL_TOPIC_FALLBACKS",
        "google.gemma-3-12b-it,us.anthropic.claude-haiku-4-5-20251001-v1:0",
    ).split(",")
    if model_id.strip()
]

# The brain. Answer quality on nuanced consulting questions is what a visitor
# actually judges the product on.
MODEL_BRAIN = os.environ.get("CADRE_MODEL_BRAIN", "us.anthropic.claude-opus-5")

# Final gate on the complete streamed answer.
MODEL_GUARD = os.environ.get("CADRE_MODEL_GUARD", "us.anthropic.claude-haiku-4-5-20251001-v1:0")

# Verdicts are one token; the ceiling exists so a model that decides to explain
# itself costs a few tokens rather than a turn budget.
JUDGE_MAX_TOKENS = int(os.environ.get("CADRE_JUDGE_MAX_TOKENS", "8"))

# CloudFront cuts an origin response at 60s and heartbeats do not extend it
# (KB-004), so the brain's generation has to fit the turn budget with the five
# other steps. This cap is the enforcement; `persona.SYSTEM_PROMPT` asks for
# the same brevity, so the answer ends rather than gets truncated.
BRAIN_MAX_TOKENS = int(os.environ.get("CADRE_BRAIN_MAX_TOKENS", "700"))

# Streamed as tokens when the topic classifier routes a turn to a human.
ESCALATION_TEXT = (
    "That one is better answered by a person on the Cadre AI team. "
    f"You can book a call with us at {CONTACT_URL} and we will pick it up from there."
)

# What the visitor sees when a step refuses the turn, keyed by the step that
# refused. Deliberately non-specific about *why* a guard fired: an explanation
# of the check is a map for getting around it.
REFUSAL_TEXTS: dict[str, str] = {
    "validate_input": (
        "I could not accept that message. Please try again with a shorter, plain-text "
        "question about Cadre AI."
    ),
    "injection_check": (
        "I can only help with questions about Cadre AI, and I cannot act on instructions "
        "about how I work. Ask me about our services and I will gladly help."
    ),
    "topic_classifier": (
        "I am the Cadre AI support assistant, so I can only help with questions about "
        "Cadre AI — our services, industries, and how to get started."
    ),
    "output_safety": (
        "I started an answer I am not confident enough to stand behind, so I have pulled "
        f"it back. Please rephrase the question, or reach us at {CONTACT_URL}."
    ),
}

ERROR_TEXT = "Something went wrong on our side. Please try again."
