"""Turn-level configuration and the user-facing copy the engine can emit.

Everything a visitor might read that is *not* generated by a model lives here:
refusal texts, the escalation text, the greeting and the suggestion chips. One
file means the copy can be reviewed without reading the graph, and the graph
never inlines a sentence.
"""

from __future__ import annotations

import os

# Mirrored by the web composer's cap; keep the two equal or the client will
# happily send a message the server refuses.
MAX_INPUT_LEN = 2000

# Answers stream in fragments so the client exercises its incremental-render
# path. A single-chunk reply would let a broken token handler pass unnoticed.
CHUNK_SIZE = 8

# Comment heartbeat cadence while a step is slow. Keeps intermediaries from
# reaping an idle-looking connection — it does not extend CloudFront's hard 60s
# origin-response cap (KB-004), which is a budget for the whole turn.
PING_INTERVAL_S = 15.0

# Per-instance turn budget. One Lambda invoke serves one request and instances
# are short-lived, so a sliding window per client is enough to blunt a flood
# without a distributed store (plan.md defers a DynamoDB token bucket).
RATE_LIMIT_TURNS = int(os.environ.get("CADRE_RATE_LIMIT_TURNS", "30"))
RATE_LIMIT_WINDOW_S = float(os.environ.get("CADRE_RATE_LIMIT_WINDOW_S", "60"))

CONTACT_URL = "https://www.cadreai.com/contact"

GREETING = "Ask me about Cadre AI — what we do, who we work with, and how to get started."
SUGGESTIONS = ["What does Cadre AI do?"]

# Streamed as tokens when the topic classifier routes a turn to a human.
ESCALATION_TEXT = (
    "That one is better answered by a person on the Cadre AI team. "
    f"You can book a call with us at {CONTACT_URL} and we will pick it up from there."
)

# What the visitor sees when a step refuses the turn, keyed by the step that
# refused. Deliberately non-specific about *why* a guard fired: an explanation
# of the check is a map for getting around it.
REFUSAL_TEXTS: dict[str, str] = {
    "validate_input": (
        "I could not accept that message. Please try again with a shorter, plain-text "
        "question about Cadre AI."
    ),
    "injection_check": (
        "I can only help with questions about Cadre AI, and I cannot act on instructions "
        "about how I work. Ask me about our services and I will gladly help."
    ),
    "topic_classifier": (
        "I am the Cadre AI support assistant, so I can only help with questions about "
        "Cadre AI — our services, industries, and how to get started."
    ),
    "output_safety": (
        "I started an answer I am not confident enough to stand behind, so I have pulled "
        f"it back. Please rephrase the question, or reach us at {CONTACT_URL}."
    ),
}

ERROR_TEXT = "Something went wrong on our side. Please try again."
