"""Turn-level configuration and the user-facing copy the engine can emit.

Everything a visitor might read that is *not* generated by a model lives here:
refusal texts, the escalation text, the greeting and the suggestion chips. One
file means the copy can be reviewed without reading the graph, and the graph
never inlines a sentence.

The greeting, the chips and the contact URL are re-exported from
`app.persona` rather than restated: they are the persona's copy, and the
brain has to be able to answer for every chip `/config` advertises. One
definition, imported one way — persona never imports this module back.
"""

from __future__ import annotations

import os

from app.persona import CONTACT_URL, GREETING, SUGGESTIONS

__all__ = [
    "CONTACT_URL",
    "GREETING",
    "SUGGESTIONS",
]

# Mirrored by the web composer's cap; keep the two equal or the client will
# happily send a message the server refuses.
MAX_INPUT_LEN = 2000

# Answers stream in fragments so the client exercises its incremental-render
# path. A single-chunk reply would let a broken token handler pass unnoticed.
CHUNK_SIZE = 8

# Comment heartbeat cadence while a step is slow. Keeps intermediaries from
# reaping an idle-looking connection — it does not extend CloudFront's hard 60s
# origin-response cap (KB-004), which is a budget for the whole turn.
PING_INTERVAL_S = 15.0

# Per-instance turn budget. One Lambda invoke serves one request and instances
# are short-lived, so a sliding window per client is enough to blunt a flood
# without a distributed store (plan.md defers a DynamoDB token bucket).
RATE_LIMIT_TURNS = int(os.environ.get("CADRE_RATE_LIMIT_TURNS", "30"))
RATE_LIMIT_WINDOW_S = float(os.environ.get("CADRE_RATE_LIMIT_WINDOW_S", "60"))

# ── Bedrock (Mantle, OpenAI-compatible) ────────────────────────────────────
#
# Transport is plain HTTPS with a bearer token, not SigV4 — see ADR 0002. The
# ids below are the ones verified invokable on this account through
# `GET /v1/models` plus a real completion; `scripts/assert_models.py` re-checks
# them before an image is ever pushed, because every model step fails open and
# a wrong id therefore ships as a *working* chat with amber rails rather than
# as a crash (KB-009).
#
# Every id is env-overridable. Several Claude ids appear in `/v1/models` but
# do not answer through this transport: the Mantle host only serves the
# OpenAI-compatible `/v1/chat/completions` surface, which 400s on a Claude id,
# and Claude's own surface (`/v1/messages`) 404s on this host entirely — it is
# an API-surface split, not an entitlement gap. The overrides are the flip
# switch for the day a Claude-compatible surface is reachable here.

BEDROCK_MANTLE_BASE_URL = os.environ.get(
    "BEDROCK_MANTLE_BASE_URL", "https://bedrock-mantle.us-east-1.api.aws/v1"
)

# Cheap SLM sanity/validity judge, second half of `validate_input`.
# A different provider from the topic primary on purpose: this step has no
# fallback, so it should not share a failure mode with anything else.
MODEL_VALIDATE = os.environ.get("CADRE_MODEL_VALIDATE", "nvidia.nemotron-nano-12b-v2")

# Strict prompt-injection classifier.
MODEL_INJECTION = os.environ.get("CADRE_MODEL_INJECTION", "qwen.qwen3-32b")

# Three-way route: in_scope / off_topic / needs_human.
#
# `nvidia.nemotron-nano-9b-v2` led this chain until live probing retired it on
# three counts: an intermittent 503 on this account (~2 calls in 5 in one
# burst, at any token budget), ~4x the latency of every alternative (p50 1.96s
# vs ~0.5s), and a reasoning monologue that has to be stripped before the
# verdict is readable. Measured over 7 cases x 2 runs with the real parser:
#
#   google.gemma-3-12b-it             14/14 http  14/14 correct  p50 0.50s
#   zai.glm-4.7-flash                 14/14       14/14          p50 0.44s
#   mistral.ministral-3-14b-instruct  14/14       14/14          p50 0.77s
#   nvidia.nemotron-nano-3-30b        14/14       12/14          p50 0.52s
#   nvidia.nemotron-nano-9b-v2        14/14       12/14          p50 1.96s
MODEL_TOPIC = os.environ.get("CADRE_MODEL_TOPIC", "google.gemma-3-12b-it")

# Walked in order when the primary *errors*. Three providers, three failure
# modes: a fallback that shares the primary's outage is not a fallback.
MODEL_TOPIC_FALLBACKS = [
    model_id.strip()
    for model_id in os.environ.get(
        "CADRE_MODEL_TOPIC_FALLBACKS",
        "nvidia.nemotron-nano-3-30b,mistral.ministral-3-14b-instruct",
    ).split(",")
    if model_id.strip()
]

# The brain.
MODEL_BRAIN = os.environ.get("CADRE_MODEL_BRAIN", "qwen.qwen3-32b")

# Final gate on the complete streamed answer.
MODEL_GUARD = os.environ.get("CADRE_MODEL_GUARD", "qwen.qwen3-32b")

# Step → display name for the model that runs it, served by /config so the
# web stepper can label each chip. `retrieve` has no model id yet — it reports
# `skipped`/`kb_not_wired` without calling a model, so it is absent on purpose.
# The values below are readable shorthand; keep them in sync when MODEL_* ids
# change.
_MODEL_DISPLAY = {
    MODEL_VALIDATE: "nemotron 12b",
    MODEL_INJECTION: "qwen3-32b",
    MODEL_TOPIC: "gemma-3-12b",
    MODEL_BRAIN: "qwen3-32b",
    MODEL_GUARD: "qwen3-32b",
}

STEP_MODELS: dict[str, str] = {
    step: _MODEL_DISPLAY[model_id]
    for step, model_id in (
        ("validate_input", MODEL_VALIDATE),
        ("injection_check", MODEL_INJECTION),
        ("topic_classifier", MODEL_TOPIC),
        ("brain", MODEL_BRAIN),
        ("output_safety", MODEL_GUARD),
    )
}

# Deliberately generous, not tiny. Several models in the roster reason before
# answering, and one truncated mid-monologue never reaches its verdict — the
# same failure family as the `gpt-oss-safeguard` gotcha. The ceiling costs
# nothing on a terse model, because temperature 0 stops it as soon as it has
# said the word.
JUDGE_MAX_TOKENS = int(os.environ.get("CADRE_JUDGE_MAX_TOKENS", "512"))
JUDGE_TEMPERATURE = float(os.environ.get("CADRE_JUDGE_TEMPERATURE", "0"))

# CloudFront cuts an origin response at 60s and heartbeats do not extend it
# (KB-004), so the brain's generation has to fit the turn budget alongside four
# judge calls. This cap is the enforcement; `persona.SYSTEM_PROMPT` asks for
# the same brevity, so the answer ends rather than gets truncated.
BRAIN_MAX_TOKENS = int(os.environ.get("CADRE_BRAIN_MAX_TOKENS", "700"))
BRAIN_TEMPERATURE = float(os.environ.get("CADRE_BRAIN_TEMPERATURE", "0.4"))

# Streamed as tokens when the topic classifier routes a turn to a human.
ESCALATION_TEXT = (
    "That one is better answered by a person on the Cadre AI team. "
    f"You can book a call with us at {CONTACT_URL} and we will pick it up from there."
)

# What the visitor sees when a step refuses the turn, keyed by the step that
# refused. Deliberately non-specific about *why* a guard fired: an explanation
# of the check is a map for getting around it.
REFUSAL_TEXTS: dict[str, str] = {
    "validate_input": (
        "I could not accept that message. Please try again with a shorter, plain-text "
        "question about Cadre AI."
    ),
    "injection_check": (
        "I can only help with questions about Cadre AI, and I cannot act on instructions "
        "about how I work. Ask me about our services and I will gladly help."
    ),
    "topic_classifier": (
        "I am the Cadre AI support assistant, so I can only help with questions about "
        "Cadre AI — our services, industries, and how to get started."
    ),
    "output_safety": (
        "I started an answer I am not confident enough to stand behind, so I have pulled "
        f"it back. Please rephrase the question, or reach us at {CONTACT_URL}."
    ),
}

ERROR_TEXT = "Something went wrong on our side. Please try again."
